CREATE TABLE company(
  compId INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  compName VARCHAR(255) NOT NULL,
  compPhone VARCHAR(20) NOT NULL,
  compAddress VARCHAR(255) NOT NULL
);

CREATE TABLE category(
  catId INT(11) PRIMARY KEY AUTO_INCREMENT NOT NULL,
  catName VARCHAR(255) NOT NULL
);

CREATE TABLE shop(
  shopId INT(11) AUTO_INCREMENT NOT NULL PRIMARY KEY,
  shopName VARCHAR(255) NOT NULL,
  shopPhone VARCHAR(20) NOT NULL,
  shopAddress VARCHAR(255) NOT NULL
);

CREATE TABLE medicine(
  medId INT(11) AUTO_INCREMENT NOT NULL PRIMARY KEY,
  medPrice DECIMAL(10, 2) NOT NULL,
  compId INT(11) NOT NULL,
  catId INT(11) NOT NULL,
  FOREIGN KEY(compId) REFERENCES company(compId) ON DELETE CASCADE,
  FOREIGN KEY(catId) REFERENCES category(catId) ON DELETE CASCADE
);